INSERT INTO HECHIZOS  (id, nombre, coste_zeon, tipo_via, int_requerida, descripcion, nivel_hechizo, efecto, libre_acceso, via, tipo_hechizo, tipo, mantenimiento, accion) VALUES (1, 'Crear Luz', '20, 50, 100, 200', 0, '5, 8, 10, 12', 'Crea una fuente de luz en un punto u objeto determinado por el hechicero.', 2, '@Base: 5 metros de zona iluminada. @Intermedio: 25 metros de zona iluminada. @Avanzado: 100 metros de zona iluminada. @Arcano: 500 metros de zona iluminada.', 0, 1, 0, 'Efecto', '5 / 5 / 10 / 15 Diario', 1)

INSERT INTO HECHIZOS (id, nombre, coste_zeon, tipo_via, int_requerida, descripcion, nivel_hechizo, efecto, libre_acceso, via, tipo_hechizo, tipo, mantenimiento, accion) VALUES (2, 'Imbuir Calma', '40, 80, 120, 160', 0, '5, 8, 11, 14', 'Tranquiliza a los individuos perturbados por un sentimiento de temor u odio que se encuentren alrededor del lanzador. Hace desaparecer cualquier estado de Miedo, Terror o Ira en el que estén sumidos, incluso si es de origen sobrenatural. De cualquier modo, no eliminará acciones violentas si estas se realizan a sangre fría o premeditadamente.', 6, '@Base: RM o RP 80 / 10 metros de radio. @Intermedio: RM o RP 100 / 25 metros de radio. @Avanzado: RM o RP 120 / 50 metros de radio. @Arcano: RM o RP 150 / 100 metros de radio.', 0, 1, 0, 'Anímico', 'No', 1)

INSERT INTO HECHIZOS (id, nombre, coste_zeon, tipo_via, int_requerida, descripcion, nivel_hechizo, efecto, libre_acceso, via, tipo_hechizo, tipo, mantenimiento, accion) VALUES (3, 'Flash Cegador', '50, 100, 150, 200', 0, '6, 9, 11, 14', 'Causa un repentino flash de luz en un radio alrededor del brujo que ciega a cualquiera que lo mire durante tantos asaltos como número de decenas por las que no supere la RF del conjuro. No es posible designar blancos específicos en el interior del flash, afectando automáticamente a todos por igual salvo al lanzador. Si alguien se está cubriendo los ojos o prevé de algún modo el resplandor, podrá aplicar un +40 a su RF', 8, '@Base: 10 metros de radio / 140 RF. @Intermedio: 25 metros de radio / 140 RF. @Avanzado: 50 metros de radio / 140 RF. @Arcano: 100 metros de radio / 160 RF.', 0, 1, 0, 'Automático', 'No', 1)

INSERT INTO HECHIZOS (id, nombre, coste_zeon, tipo_via, int_requerida, descripcion, nivel_hechizo, efecto, libre_acceso, via, tipo_hechizo, tipo, mantenimiento, accion) VALUES (4, 'Escudo de Luz', '50, 120, 180, 250', 0, '6, 8, 10, 14', ' Forma una barrera de energía, que protege frente a cualquier fuente de ataque. El escudo sólo puede ser dañado por ataques de naturaleza sobrenatural, aunque los impactos basados en oscuridad causarán doble daño sobre él.', 10, '@Base: El escudo tiene 300 puntos de Resistencia. @Intermedio: El escudo tiene 1.000 puntos de Resistencia. @Avanzado: El escudo tiene 1.800 puntos de Resistencia. @Arcano: El escudo tiene 3.000 puntos de Resistencia.', 0, 1, 0, 'Defensa', '5 / 15 / 20 / 25', 0)

INSERT INTO HECHIZOS (id, nombre, coste_zeon, tipo_via, int_requerida, descripcion, nivel_hechizo, efecto, libre_acceso, via, tipo_hechizo, tipo, mantenimiento, accion) VALUES (5, 'Percibir', '50, 150, 200, 250', 0, '6, 9, 12, 14', 'Este conjuro aumenta la percepción del hechicero acrecentando sus habilidades secundarias de Advertir y Buscar, así como su Valoración mágica en el caso de que pretenda medir o detectar el potencial mágico de algo o alguien (nunca para ocultarlo) así como para analizar la naturaleza de otros conjuros.', 12, '@Base: +50 Advertir, Buscar y Valoración mágica. @Intermedio: +150 Advertir, Buscar y Valoración mágica. @Avanzado: +200 Advertir, Buscar y Valoración mágica. @Arcano: +250 Advertir, Buscar y Valoración mágica.', 0, 1, 0, 'Efecto', '5 / 15 / 20 / 25', 1)

INSERT INTO HECHIZOS (id, nombre, coste_zeon, tipo_via, int_requerida, descripcion, nivel_hechizo, efecto, libre_acceso, via, tipo_hechizo, tipo, mantenimiento, accion) VALUES (6, 'Armadura de Luz', '60, 90, 120, 150', 0, '6, 9, 12, 15', 'Forma una coraza mística que otorga TA a su usuario contra todo tipo de ataque, en especial contra los basados en energía. Aunque cuenta como una armadura, no se aplican penalizadores al turno por emplear capas de protección adicionales.', 16, '@Base: TA 2 en Energía y TA 1 en el resto. @Intermedio: TA 5 en Energía y TA 2 en el resto. @Avanzado: TA 8 en Energía y TA 4 en el resto. @Arcano: TA 12 en Energía y TA 6 en el resto.', 0, 1, 0, 'Efecto', '5 / 10 / 15 / 20', 1)

INSERT INTO HECHIZOS (id, nombre, coste_zeon, tipo_via, int_requerida, descripcion, nivel_hechizo, efecto, libre_acceso, via, tipo_hechizo, tipo, mantenimiento, accion) VALUES (7, 'Destrucción de Sombras', '60, 100, 150, 250', 0, '6, 9, 12, 15', 'Destruye las sombras existentes alrededor del hechicero. Si se lanza sobre seres basados naturalmente en oscuridad, estos deberán superar una RM o perderán una cantidad equivalente al doble de su nivel de fracaso en puntos de vida (por diez, si poseen acumulación de daño). Mientras se mantenga el conjuro, las entidades afectadas deberán realizar un nuevo control de RM cada asalto', 18, '@Base: 10 metros de radio / 140 RM. @Intermedio: 100 metros de radio / 180 RM. @Avanzado: 250 metros de radio / 220 RM. @Arcano: 500 metros de radio / 280 RM.', 0, 1, 0, 'Efecto, Anímico', '10 / 10 / 15 / 25', 1)

INSERT INTO HECHIZOS (id, nombre, coste_zeon, tipo_via, int_requerida, descripcion, nivel_hechizo, efecto, libre_acceso, via, tipo_hechizo, tipo, mantenimiento, accion) VALUES (8, 'Detectar lo Negativo', '50, 100, 160, 280', 0, '6, 9, 12, 15', 'Detecta cualquier sentimiento negativo, como odio, miedo o ira, que se encuentre un radio alrededor del lanzador, que no sea capaz de resistir la RM del conjuro. De igual forma, el mago también percibe las criaturas elementales basadas en dichas emociones.', 20, '@Base: 25 metros de radio / 80 RM para resistirse. @Intermedio: 150 metros de radio / 140 RM para resistirse. @Avanzado: 500 metros de radio / 160 RM para resistirse. @Arcano: 1 kilómetro de radio / 200 RM para resistirse', 0, 1, 0, 'Detecció', '5 / 10 / 20 / 30', 1)

INSERT INTO HECHIZOS (id, nombre, coste_zeon, tipo_via, int_requerida, descripcion, nivel_hechizo, efecto, libre_acceso, via, tipo_hechizo, tipo, mantenimiento, accion) VALUES (9, 'Descarga de Luz', '50, 90, 120, 150', 0, '6, 9, 12, 15', 'Proyecta una descarga de energía mágica basada en luz. El ataque se realiza en la TA de Energía.', 22, '@Base: Daño 60. @Intermedio: Daño 90. @Avanzado: Daño 120. @Arcano: Daño 150.', 0, 1, 0, 'Ataque', 'No', 1)

INSERT INTO HECHIZOS (id, nombre, coste_zeon, tipo_via, int_requerida, descripcion, nivel_hechizo, efecto, libre_acceso, via, tipo_hechizo, tipo, mantenimiento, accion) VALUES (10, 'Holograma', '40, 150, 250, 350', 0, '6, 9, 12, 15', ' Crea una forma luminosa inmaterial a la que el hechicero podrá darle la apariencia y el movimiento que desee, haciendo muy difícil diferenciarla de un verdadero ser u objeto. Si se crea una criatura, podrá realizar cualquier acción inhumana que el controlador desee, pero imitará las habilidades físicas del hechicero. Si, por ejemplo, se utiliza el holograma para simular que se va a realizar un ataque, utilizará la habilidad de combate de su lanzador. El holograma no puede tocar a nadie ni ser tocado, pero si recibe algún daño basado en energía, desaparece. Para poder percibir que se trata sólo de una imagen, es necesario superar un control de Advertir contra una dificultad de Casi Imposible, o un Buscar contra Muy Difícil.', 26, '@Base: La imagen tiene un tamaño máximo de un metro cuadrado. @Intermedio: La imagen tiene un tamaño máximo de 15 metros cuadrados. @Avanzado: La imagen tiene un tamaño máximo de 50 metros cuadrados. @Arcano: La imagen tiene un tamaño máximo de 100 metros cuadrados y la dificultad del control de Advertir y buscar aumenta respectivamente a Imposible y Absurdo.', 0, 1, 0, 'Efecto', '5 / 20 / 25 / 30', 1)

INSERT INTO HECHIZOS (id, nombre, coste_zeon, tipo_via, int_requerida, descripcion, nivel_hechizo, efecto, libre_acceso, via, tipo_hechizo, tipo, mantenimiento, accion) VALUES (11, 'Lazos de Luz', '60, 100, 140, 180', 0, '6, 9, 12, 15', 'Forma unos lazos de luz que sujetan al blanco designado. Para ello el lanzador emplea las reglas de Presa, aunque sin penalizador alguno a su habilidad. Los lazos de luz no pueden romperse por el sujeto al que sujetan, pero si un tercero intenta romperlos, estos se consideran un arma de energía con Entereza 25.', 28, '@Base: Disponen de una Fuerza base 8 para los controles. @Intermedio: Disponen de una Fuerza base 12 para los controles. @Avanzado: Disponen de una Fuerza base 15 para los controles y tienen Entereza 30. @Arcano: Disponen de una Fuerza base 18 para los controles y tienen Entereza 35.', 0, 1, 0, 'Ataque', '10 / 10 / 15 / 15', 1)

